version: "3.3"

services:
  bui-api-people:
    image: bui-api-people:latest
    build: .
    ports:
      - "8200:8200"
    env_file:
      - .env.local

    volumes:
      - /Users/vesko/coding/toni/bui2/local/data/bui_api_people:/app/config
 